database:
  db_location: C:\Users\santosh.a.d.kulkarni\PycharmProjects\PRtool_alphav1\entities\instance\
  db_name: isr_database.db
  db_secret_key: 5D4C1
  password_reset_value: test123
  db_table_names:
    users: isr_registered_users
    issues: isr_issues